In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\HP\Downloads\mini projectnew2\Data\Traffic_Violations.csv",
    low_memory=False
)

print(df.shape)

(1048575, 35)

In [2]:
df.head(10)

,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,Belts,...,Charge,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
0,09/24/2013,17:11:00,MCP,"3rd district, Silver Spring",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,8804 FLOWER AVE,NaN,NaN,No,No,...,13-401(h),Transportation Article,No,BLACK,M,TAKOMA PARK,MD,MD,A - Marked Patrol,NaN
1,08/29/2017,10:19:00,MCP,"2nd district, Bethesda",DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC...,WISCONSIN AVE@ ELM ST,38.981725,-77.092757,No,No,...,21-201(a1),Transportation Article,No,WHITE,F,FAIRFAX STATION,VA,VA,A - Marked Patrol,"(38.981725, -77.0927566666667)"
2,12-01-2014,12:52:00,MCP,"6th district, Gaithersburg / Montgomery Village",FAILURE STOP AND YIELD AT THRU HWY,CHRISTOPHER AVE/MONTGOMERY VILLAGE AVE,39.162888,-77.229088,No,No,...,21-403(b),Transportation Article,No,BLACK,F,UPPER MARLBORO,MD,MD,A - Marked Patrol,"(39.1628883333333, -77.2290883333333)"
3,08/29/2017,09:22:00,MCP,"3rd district, Silver Spring",FAILURE YIELD RIGHT OF WAY ON U TURN,CHERRY HILL RD./CALVERTON BLVD.,39.056975,-76.954633,No,No,...,21-402(b),Transportation Article,No,BLACK,M,FORT WASHINGTON,MD,MD,A - Marked Patrol,"(39.056975, -76.9546333333333)"
4,08/28/2017,23:41:00,MCP,"6th district, Gaithersburg / Montgomery Village",FAILURE OF DR. TO MAKE LANE CHANGE TO AVAIL. L...,355 @ SOUTH WESTLAND DRIVE,NaN,NaN,No,No,...,21-405(e1),Transportation Article,No,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,NaN
5,08/27/2013,00:55:00,MCP,"2nd district, Bethesda",NEGLIGENT DRIVING VEHICLE IN CARELESS AND IMPR...,CONNECTICUT/CHEVY CHASE LAKE,NaN,NaN,No,No,...,21-901.1(b),Transportation Article,No,WHITE,F,SILVER SPRING,MD,MD,A - Marked Patrol,NaN
6,10-08-2013,13:23:00,MCP,"4th district, Wheaton",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,GEORGIA AVE / BEL PRE RD,39.093383,-77.079552,No,No,...,13-401(h),Transportation Article,No,HISPANIC,M,BELTSVILLE,MD,MD,A - Marked Patrol,"(39.0933833333333, -77.0795516666667)"
7,04/24/2015,00:38:00,MCP,"1st district, Rockville",DRIVER FAIL TO STOP AT FLASHING RED TRAFFIC SI...,EB MONTROSE PKWY/EAST JEFFERSON ST,NaN,NaN,No,No,...,21-204(b),Transportation Article,No,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,NaN
8,08/28/2017,23:41:00,MCP,"6th district, Gaithersburg / Montgomery Village",FAILURE OF INDIVIDUAL DRIVING ON HIGHWAY TO DI...,355 @ SOUTH WESTLAND DRIVE,NaN,NaN,No,No,...,16-112(c),Transportation Article,No,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,NaN
9,08/28/2017,23:41:00,MCP,"6th district, Gaithersburg / Montgomery Village",DRIVING VEHICLE ON HIGHWAY WITH AN EXPIRED LIC...,355 @ SOUTH WESTLAND DRIVE,NaN,NaN,No,No,...,16-115(g),Transportation Article,No,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,NaN

In [3]:
df = df.sample(n=300000, random_state=42)

print(df.shape)

(300000, 35)

In [13]:
df.columns = (
    df.columns
      .str.strip()
    .str.lower()# remove extra spaces
      .str.replace(" ", "_")    # spaces → underscore
      .str.replace("/", "_")    # slash → underscore
      .str.replace("-", "_")    # dash → underscore
)

In [14]:
df.columns

Index(['date_of_stop', 'time_of_stop', 'agency', 'subagency', 'description',
       'location', 'latitude', 'longitude', 'accident', 'belts',
       'personal_injury', 'property_damage', 'fatal', 'commercial_license',
       'hazmat', 'commercial_vehicle', 'alcohol', 'work_zone', 'state',
       'vehicletype', 'year', 'make', 'model', 'color', 'violation_type',
       'charge', 'article', 'contributed_to_accident', 'race', 'gender',
       'driver_city', 'driver_state', 'dl_state', 'arrest_type',
       'geolocation'],
      dtype='object')

In [15]:
df = df.rename(columns={
    "vehicletype": "vehicle_type",
    "date_of_stop": "stop_date",
    "time_of_stop": "stop_time"
})

In [16]:
df.columns

Index(['stop_date', 'stop_time', 'agency', 'subagency', 'description',
       'location', 'latitude', 'longitude', 'accident', 'belts',
       'personal_injury', 'property_damage', 'fatal', 'commercial_license',
       'hazmat', 'commercial_vehicle', 'alcohol', 'work_zone', 'state',
       'vehicle_type', 'year', 'make', 'model', 'color', 'violation_type',
       'charge', 'article', 'contributed_to_accident', 'race', 'gender',
       'driver_city', 'driver_state', 'dl_state', 'arrest_type',
       'geolocation'],
      dtype='object')

In [17]:
df.isna().sum().sort_values(ascending=False).head(10)

geolocation    20975
longitude      20975
latitude       20975
article        15334
color           3665
year            1970
dl_state         121
driver_city       46
model             26
make              12
dtype: int64

In [18]:
df["latitude"] = df["latitude"].fillna(df["latitude"].median())
df["longitude"] = df["longitude"].fillna(df["longitude"].median())

In [19]:
df["geolocation"] = df["geolocation"].fillna("Unknown")

In [20]:
categorical_nan_cols = [
    "article",
    "color",
    "dl_state",
    "driver_city",
    "model",
    "make"
]

df[categorical_nan_cols] = df[categorical_nan_cols].fillna("Unknown")

In [21]:
df["year"] = df["year"].fillna(df["year"].median()).astype(int)

In [22]:
df.isna().sum().sort_values(ascending=False).head(10)

state           6
driver_state    2
description     1
subagency       1
agency          0
stop_date       0
stop_time       0
longitude       0
accident        0
belts           0
dtype: int64

In [23]:
remaining_object_nan_cols = [
    "state",
    "driver_state",
    "description",
    "subagency"
]

In [24]:
df[remaining_object_nan_cols] = df[remaining_object_nan_cols].fillna("Unknown")

In [25]:
df.isna().sum().sort_values(ascending=False).head(10)

stop_date      0
stop_time      0
agency         0
subagency      0
description    0
location       0
latitude       0
longitude      0
accident       0
belts          0
dtype: int64

In [26]:
# Select object columns
object_cols = df.select_dtypes(include="object").columns

# Count empty or whitespace-only values
empty_counts = {}

for col in object_cols:
    empty_counts[col] = ((df[col].str.strip() == "")).sum()

# Show columns with empty values
pd.Series(empty_counts).sort_values(ascending=False).head(10)

stop_date          0
stop_time          0
agency             0
subagency          0
description        0
location           0
accident           0
belts              0
personal_injury    0
property_damage    0
dtype: int64

In [27]:
df.head(5)

,stop_date,stop_time,agency,subagency,description,location,latitude,longitude,accident,belts,...,charge,article,contributed_to_accident,race,gender,driver_city,driver_state,dl_state,arrest_type,geolocation
781974,04/28/2015,09:49:00,MCP,"4th district, Wheaton",DRIVING IN LEFT TURN LANE LONGER DISTANCE THAN...,9420 GEORGIA AVE,39.009382,-77.040707,No,No,...,21-309(h),Transportation Article,No,BLACK,F,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0093816666667, -77.0407066666667)"
937737,02/18/2017,10:34:00,MCP,"1st district, Rockville",EXCEEDING POSTED MAXIMUM SPEED LIMIT: 80 MPH I...,SB RT270 @ RT370,39.117340,-77.194780,No,No,...,21-801.1,Transportation Article,No,BLACK,M,GAITHERSBURG,MD,MD,I - Marked Moving Radar (Moving),"(39.11734, -77.19478)"
907828,12/28/2016,01:07:00,MCP,"1st district, Rockville",PERSON DRIVING MOTOR VEHICLE WHILE LICENSE SUS...,MONTROSE PKWY / E JEFFERSON ST,39.050968,-77.127065,No,No,...,16-303(h),Transportation Article,No,HISPANIC,F,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.0509683333333, -77.127065)"
784628,04/21/2015,15:58:00,MCP,"2nd district, Bethesda",DRIVER USING HANDS TO USE HANDHELD TELEPHONE W...,DEMOCRACY / WESTLAKE,39.021317,-77.138815,No,No,...,21-1124.2(d2),Transportation Article,No,WHITE,F,WASHINGTON,DC,DC,A - Marked Patrol,"(39.0213166666667, -77.138815)"
662460,02-05-2016,22:37:00,MCP,"1st district, Rockville",DRIVER CHANGING LANES WHEN UNSAFE,355 @ MARINELLI,39.047368,-77.109993,No,No,...,21-309(b),Transportation Article,No,WHITE,M,BETHESDA,MD,MD,B - Unmarked Patrol,"(39.0473683333333, -77.1099933333333)"

In [28]:
df["stop_date"] = pd.to_datetime(df["stop_date"], errors="coerce")

In [29]:
df["stop_time"] = pd.to_datetime(df["stop_time"], format="%H:%M:%S", errors="coerce").dt.time

In [30]:
df[["stop_date", "stop_time"]].dtypes

stop_date    datetime64[ns]
stop_time            object
dtype: object

In [31]:
df["stop_hour"] = df["stop_time"].apply(
    lambda x: x.hour if pd.notnull(x) else -1
)

df["stop_day"] = df["stop_date"].dt.day
df["stop_month"] = df["stop_date"].dt.month
df["stop_weekday"] = df["stop_date"].dt.weekday

In [32]:
# Total duplicate rows
df.duplicated().sum()

np.int64(117)

In [33]:
df = df.drop_duplicates()

In [49]:
df.to_csv(
    r"C:\Users\HP\Downloads\mini projectnew2\Data\cleaned_stop_level_dataset.csv",
    index=False
)

print("✅ Stop-level cleaned dataset saved for visualization")

✅ Stop-level cleaned dataset saved for visualization

In [34]:
df["vehicle_id"] = (
    df["make"].astype(str) + "_" +
    df["model"].astype(str) + "_" +
    df["year"].astype(str)
)

In [35]:
vehicle_df = df.groupby("vehicle_id").agg(
    total_violations=("vehicle_id", "count"),
    accident_count=("accident", lambda x: (x == "Yes").sum()),
    alcohol_count=("alcohol", lambda x: (x == "Yes").sum()),
    fatal_count=("fatal", lambda x: (x == "Yes").sum()),
    property_damage_count=("property_damage", lambda x: (x == "Yes").sum()),
    avg_stop_hour=("stop_hour", "mean"),
    unique_locations=("location", "nunique")
).reset_index()

In [36]:
threshold = vehicle_df["total_violations"].quantile(0.90)

vehicle_df["repeat_risk"] = (
    vehicle_df["total_violations"] >= threshold
).astype(int)

In [37]:
vehicle_df["repeat_risk"].value_counts()

repeat_risk
0    42101
1     4724
Name: count, dtype: int64

In [38]:
vehicle_df.columns

Index(['vehicle_id', 'total_violations', 'accident_count', 'alcohol_count',
       'fatal_count', 'property_damage_count', 'avg_stop_hour',
       'unique_locations', 'repeat_risk'],
      dtype='object')

In [39]:
df.head()

,stop_date,stop_time,agency,subagency,description,location,latitude,longitude,accident,belts,...,driver_city,driver_state,dl_state,arrest_type,geolocation,stop_hour,stop_day,stop_month,stop_weekday,vehicle_id
781974,2015-04-28,09:49:00,MCP,"4th district, Wheaton",DRIVING IN LEFT TURN LANE LONGER DISTANCE THAN...,9420 GEORGIA AVE,39.009382,-77.040707,No,No,...,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0093816666667, -77.0407066666667)",9,28.0,4.0,1.0,FORD_AEROSTAR_1997
937737,2017-02-18,10:34:00,MCP,"1st district, Rockville",EXCEEDING POSTED MAXIMUM SPEED LIMIT: 80 MPH I...,SB RT270 @ RT370,39.117340,-77.194780,No,No,...,GAITHERSBURG,MD,MD,I - Marked Moving Radar (Moving),"(39.11734, -77.19478)",10,18.0,2.0,5.0,VOLK_JETTA_2010
907828,2016-12-28,01:07:00,MCP,"1st district, Rockville",PERSON DRIVING MOTOR VEHICLE WHILE LICENSE SUS...,MONTROSE PKWY / E JEFFERSON ST,39.050968,-77.127065,No,No,...,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.0509683333333, -77.127065)",1,28.0,12.0,2.0,HOND_CIVIC_1992
784628,2015-04-21,15:58:00,MCP,"2nd district, Bethesda",DRIVER USING HANDS TO USE HANDHELD TELEPHONE W...,DEMOCRACY / WESTLAKE,39.021317,-77.138815,No,No,...,WASHINGTON,DC,DC,A - Marked Patrol,"(39.0213166666667, -77.138815)",15,21.0,4.0,1.0,BMW_X1_2014
662460,NaT,22:37:00,MCP,"1st district, Rockville",DRIVER CHANGING LANES WHEN UNSAFE,355 @ MARINELLI,39.047368,-77.109993,No,No,...,BETHESDA,MD,MD,B - Unmarked Patrol,"(39.0473683333333, -77.1099933333333)",22,NaN,NaN,NaN,CADI_2S_1977

In [40]:
vehicle_df.isna().sum()

vehicle_id               0
total_violations         0
accident_count           0
alcohol_count            0
fatal_count              0
property_damage_count    0
avg_stop_hour            0
unique_locations         0
repeat_risk              0
dtype: int64

In [41]:
vehicle_df.columns

Index(['vehicle_id', 'total_violations', 'accident_count', 'alcohol_count',
       'fatal_count', 'property_damage_count', 'avg_stop_hour',
       'unique_locations', 'repeat_risk'],
      dtype='object')

In [43]:
final_ml_df = vehicle_df.drop(columns=["vehicle_id", "total_violations"])

In [44]:
final_ml_df.columns

Index(['accident_count', 'alcohol_count', 'fatal_count',
       'property_damage_count', 'avg_stop_hour', 'unique_locations',
       'repeat_risk'],
      dtype='object')

In [45]:
final_ml_df.to_csv(
     r"C:\Users\HP\Downloads\mini projectnew2\Data\final_ml_dataset.csv",
    index=False
)